### ISSUE TITLE
Add descriptions to API schema

### ISSUE THREAD

**Issue by rcannood** [laminlabs/laminhub-public#16]
### Description of feature

When I make a call to [Get schema](https://us-west-2.api.lamin.ai/docs#/default/get_schema_instances__instance_id__schema_get), I get something like this:

```yaml
core:
  run:
    fields_metadata:
      id:
        type: BigAutoField
        through: ~
        field_name: id
        model_name: run
        column_name: id
        schema_name: core
        is_link_table: no
        relation_type: ~
        related_field_name: ~
        related_model_name: ~
        related_schema_name: ~
      uid:
        type: CharField
        through: ~
        field_name: uid
        model_name: run
        column_name: uid
        schema_name: core
        is_link_table: no
        relation_type: ~
        related_field_name: ~
        related_model_name: ~
        related_schema_name: ~
      parent:
        type: ForeignKey
        through:
          left_key: parent_id
          right_key: id
          link_table_name: ~
        field_name: parent
        model_name: run
        column_name: parent_id
        schema_name: core
        is_link_table: no
        relation_type: many-to-one
        related_field_name: children
        related_model_name: run
        related_schema_name: core
...
```

Could we include documentation for modules, models, and fields? I need to be able to generate the R API documentation from this schema such that it looks something like [this](https://docs.lamin.ai/lamindb.artifact#lamindb.Artifact.storage).
