### ISSUE TITLE
Make API more consistent

### ISSUE THREAD

**Issue by rcannood** [laminlabs/laminhub-public#17]
### Description of feature

When I make a call to [Get schema](https://us-west-2.api.lamin.ai/docs#/default/get_schema_instances__instance_id__schema_get), I get something like this:

```yaml
core:
  run:
    fields_metadata:
      id:
        type: BigAutoField
        through: ~
        field_name: id
        model_name: run
        column_name: id
        schema_name: core
        is_link_table: no
        relation_type: ~
        related_field_name: ~
        related_model_name: ~
        related_schema_name: ~
      uid:
        type: CharField
        through: ~
        field_name: uid
        model_name: run
        column_name: uid
        schema_name: core
        is_link_table: no
        relation_type: ~
        related_field_name: ~
        related_model_name: ~
        related_schema_name: ~
      parent:
        type: ForeignKey
        through:
          left_key: parent_id
          right_key: id
          link_table_name: ~
        field_name: parent
        model_name: run
        column_name: parent_id
        schema_name: core
        is_link_table: no
        relation_type: many-to-one
        related_field_name: children
        related_model_name: run
        related_schema_name: core
...
```

Could we make the naming system of "modules", "models", and "fields" consistent across what I'm being told to use, the API and the schema?

  - I was told by Alex that core, bionty, ... are modules, Artifact, Run, ... are registries, and that a record in a registry as fields.
  - In the API, all instances of `{model_name}` should be renamed to `{registry_name}`. For example: `POST /instances/{instance_id}/modules/{module_name}/{model_name}/{id_or_uid}`
  - In a registry's fields_metadata, the following keys should be renamed:
    - `model_name` → `registry_name`
    - `schema_name` → `module_name`
    - `related_model_name` → `related_registry_name`
    - `related_schema_name` → `related_module_name`
